add_newline = true
format = """
$git_branch\
$git_state\
$git_status\
$git_tag\
$line_break\
[](fg:black)\
[ $username ]\
(bg:black fg:254)\
$character
"""

right_format = "$directory"

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[character]
format = "[](fg:black)"

[directory]
disabled = false
before_repo_root_style = "fg:white"
format = "[$path](fg:white)"
read_only = ""
repo_root_format = "[$path](fg:white) [](fg:purple)[ $repo_root](bg:purple fg:254)[](fg:purple)"
repo_root_style = "fg:white"
truncation_length = 3

[username]
format = "$user"
show_always = true
 

