#!/bin/bash

# This test file is automatically generated by the dev-container-features test framework.
# Manual edits will be overwritten when the test is re-generated.

set -e

# Optional: Import test library
source dev-container-features-test-lib

# Definition specific tests
check "bash should be default shell" bash -c "echo $SHELL" | grep -q "/bin/bash"
check "zsh not default" test "$SHELL" != "/bin/zsh"
check "no auto_cd in bash" bash -c "shopt auto_cd 2>&1" | grep -q "invalid shell option name"
check "zoxide not aliased to cd" bash -c "type cd 2>&1" | grep -q "shell builtin"
check "starship not in prompt" bash -c "echo \$PS1" | grep -qv "starship"
check "ls is not aliased" bash -c "type ls 2>&1" | grep -q "/bin/ls"
check "cat is not aliased" bash -c "type cat 2>&1" | grep -q "/bin/cat"
check "find is not aliased" bash -c "type find 2>&1" | grep -q "/usr/bin/find"
check "grep is not aliased" bash -c "type grep 2>&1" | grep -q "/bin/grep"

# Report result
reportResults