# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Disabled starship modules
format = """
$env_var$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$fill\
$cmd_duration $time\
$line_break\
$character"""

# format = """
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_state\
# $git_status\
# $git_metrics\
# $fill\
# $nodejs\
# $cmd_duration $jobs $time\
# $line_break\
# $character"""

[directory]
style = "bright-white"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
# home_symbol = " 󰋜 "
home_symbol = "~"
read_only_style = "197"
read_only = " 󰌾 "

[line_break]
disabled = false

[character]
success_symbol = '[▸](green)'
error_symbol = '[▸](red)'
vimcmd_symbol = '[◂](green)'

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
symbol = " "

[rust]
symbol = " "

[terraform]
symbol = " "

[aws]
symbol = " "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"

[fill]
symbol = " "

[gcloud]
disabled = false
format = '[$symbol(\($region\))]($style) '
style = 'bright-black'
symbol = '󰏆'

[kubernetes]
disabled = false
format = '[$symbol(\($namespace\)@$cluster)]($style) '
style = 'bright-black'
symbol = ' '

[azure]
disabled = false
format = '[$symbol(\($subscription\))]($style) '
style = 'bright-black'
symbol = '󰠅'

[bun]
symbol = ' '

[buf]
symbol = ' '

[c]
symbol = ' '

[conda]
symbol = ' '

[crystal]
symbol = ' '

[dart]
symbol = ' '

[docker_context]
symbol = ' '

[elixir]
symbol = ' '

[elm]
symbol = ' '

[fennel]
symbol = ' '

[fossil_branch]
symbol = ' '

[golang]
symbol = ' '

[guix_shell]
symbol = ' '

[haskell]
symbol = ' '

[haxe]
symbol = ' '

[hg_branch]
symbol = ' '

[hostname]
ssh_symbol = ' '

[java]
symbol = ' '

[julia]
symbol = ' '

[kotlin]
symbol = ' '

[lua]
symbol = ' '

[meson]
symbol = '󰔷 '

[nim]
symbol = '󰆥 '

[nix_shell]
symbol = ' '

[nodejs]
symbol = ' '

[ocaml]
symbol = ' '

[os.symbols]
Alpaquita = ' '
Alpine = ' '
AlmaLinux = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '󰛓 '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = '󰈸 '
Kali = ' '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = '󰈺 '
openSUSE = ' '
OracleLinux = '󰌷 '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
RockyLinux = ' '
Redox = '󰀘 '
Solus = '󰠳 '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Void = ' '
Windows = '󰍲 '

[package]
symbol = '󰏗 '

[perl]
symbol = ' '

[php]
symbol = ' '

[pijul_channel]
symbol = ' '

[python]
symbol = ' '

[rlang]
symbol = '󰟔 '

[ruby]
symbol = ' '

[scala]
symbol = ' '

[swift]
symbol = ' '

[zig]
symbol = ' '

[username]
style_user = "green"
style_root = "red"
format = '[$user]($style) '
disabled = false
show_always = true

[env_var.user_agent]
symbol = '  '
variable = 'USER_AGENT'
default = ''
format = '[$symbol$env_value]($style)'
style = 'red'