version: '3.8'

services:
  app:
    image: ghcr.io/onezerocompany/base:latest
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    depends_on:
      - postgres
    networks:
      - dev-network

  postgres:
    image: postgres:${templateOption:postgresVersion}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${templateOption:databaseName}
      POSTGRES_USER: ${templateOption:databaseUser}
      POSTGRES_PASSWORD: ${templateOption:databasePassword}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    networks:
      - dev-network

volumes:
  postgres-data:

networks:
  dev-network: