name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-features:
    name: Validate Features
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate feature structure
        run: |
          echo "Validating feature structure..."
          for feature in features/src/*/; do
            if [ -d "$feature" ]; then
              feature_name=$(basename "$feature")
              echo "Checking feature: $feature_name"
              
              # Check required files
              if [ ! -f "$feature/devcontainer-feature.json" ]; then
                echo "ERROR: Missing devcontainer-feature.json in $feature_name"
                exit 1
              fi
              
              if [ ! -f "$feature/install.sh" ]; then
                echo "ERROR: Missing install.sh in $feature_name"
                exit 1
              fi
              
              if [ ! -f "$feature/README.md" ]; then
                echo "ERROR: Missing README.md in $feature_name"
                exit 1
              fi
              
              # Validate JSON
              jq . "$feature/devcontainer-feature.json" > /dev/null || {
                echo "ERROR: Invalid JSON in $feature_name/devcontainer-feature.json"
                exit 1
              }
              
              # Check install.sh is executable
              if [ ! -x "$feature/install.sh" ]; then
                echo "ERROR: install.sh is not executable in $feature_name"
                exit 1
              fi
            fi
          done
          echo "All features validated successfully!"

  test-features:
    name: Test Features
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features:
          - common-utils
          - docker
          - mise
          - sandbox

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test feature
        uses: devcontainers/action@v1
        with:
          generate-docs: "false"
          base-path-to-features: "./features/src"
          features-namespace: "onezerocompany/devcontainers/features"
          test-folder: "./features/test"
          filter: ${{ matrix.features }}

  build-images:
    name: Test Build Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - base
          - dind
          - devcontainer-base
          - runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./images/${{ matrix.image }}
          platforms: linux/amd64
          push: false
          tags: test-${{ matrix.image }}:latest

  lint-dockerfiles:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
          ignore: DL3008,DL3009

  validate-shell-scripts:
    name: Validate Shell Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './features/src'
          severity: warning

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'