name: Publish Dev Containers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "features/**"
      - "templates/**"
      - ".github/workflows/publish-devcontainers.yml"
  release:
    types: [published]

jobs:
  # Publish all features
  publish-features:
    name: Publish Feature - ${{ matrix.feature }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        feature: [starship] # Add more features here, e.g. [starship, another-feature, ...]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Feature
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./features/src/${{ matrix.feature }}"
          generate-docs: "true"
          disable-repo-tagging: false
          oci-registry: ghcr.io
          features-namespace: onezerocompany/feature
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Publish all templates (after features)
  publish-templates:
    name: Publish All Templates
    runs-on: ubuntu-latest
    needs: publish-features # Ensure features are published first
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish All Templates
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./templates"
          generate-docs: "true"
          disable-repo-tagging: false
          oci-registry: ghcr.io
          templates-namespace: onezerocompany/devcontainer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Pre-build dev container images
  prebuild:
    name: Pre-build Dev Container Images
    runs-on: ubuntu-latest
    needs: publish-templates # Run after templates are published
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build base template
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/onezerocompany/devcontainer-base
          cacheFrom: ghcr.io/onezerocompany/devcontainer-base
          push: always
          subFolder: templates/base
