name: Publish Dev Containers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'features/**'
      - 'templates/**'
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Features
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./features/src"
          generate-docs: "true"
          disable-repo-tagging: false
          oci-registry: ghcr.io
          features-namespace: onezerocompany/feature
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Templates
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./templates"
          generate-docs: "true"
          disable-repo-tagging: false
          oci-registry: ghcr.io
          templates-namespace: onezerocompany/devcontainer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}