name: Build and Publish Images & Features

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # Run every day at 3am
  push:
    branches:
      - main

jobs:
  base:
    name: Build and Publish Base Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./images/base
          platforms: linux/amd64,linux/arm64
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/base:buildcache
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/base:buildcache,mode=max
          tags: ghcr.io/${{ github.repository_owner }}/base:latest
          push: true

  base-docker:
    name: Build and Publish Base:Docker Image
    runs-on: ubuntu-latest
    needs: [base]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./images/base-docker
          platforms: linux/amd64,linux/arm64
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/base:docker-buildcache
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/base:docker-buildcache,mode=max
          tags: ghcr.io/${{ github.repository_owner }}/base:docker
          push: true

  base-dev:
    name: Build and Publish Base:Dev Image
    runs-on: ubuntu-latest
    needs: [base]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./images/base-dev
          platforms: linux/amd64,linux/arm64
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/base:dev-buildcache
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/base:dev-buildcache,mode=max
          tags: ghcr.io/${{ github.repository_owner }}/base:dev
          push: true

  base-dev-docker:
    name: Build and Publish Base:Dev-Docker Image
    runs-on: ubuntu-latest
    needs: [base-docker]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./images/base-dev-docker
          platforms: linux/amd64,linux/arm64
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/base:dev-docker-buildcache
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/base:dev-docker-buildcache,mode=max
          tags: ghcr.io/${{ github.repository_owner }}/base:dev-docker
          push: true

  runner:
    name: Build and Publish Runner Image
    runs-on: ubuntu-latest
    needs: [base]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./images/runner
          platforms: linux/amd64,linux/arm64
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/runner:buildcache
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/runner:buildcache,mode=max
          tags: ghcr.io/${{ github.repository_owner }}/runner:latest
          push: true

  features:
    name: Build and Publish Features
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./features/src"
          disable-repo-tagging: "true"
          features-namespace: "onezerocompany/devcontainers/features"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  devcontainers:
    name: Publish Pre-built Devcontainers (Regular)
    runs-on: ubuntu-latest
    needs: [base-dev, features]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Publish Devcontainers"
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./devcontainers"
          disable-repo-tagging: "true"
          templates-namespace: "onezerocompany/devcontainers"
          exclude-templates: "*-docker"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  devcontainers-docker:
    name: Publish Pre-built Devcontainers (Docker)
    runs-on: ubuntu-latest
    needs: [base-dev-docker, features]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Publish Docker Devcontainers"
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./devcontainers"
          disable-repo-tagging: "true"
          templates-namespace: "onezerocompany/devcontainers"
          include-templates: "*-docker"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
